In [56]:
import numpy as np
import pandas as pd

In [57]:
pd.isnull((np.nan))

True

## Pandas Operations With Missing Values

In [58]:
s = pd.Series([1, 2, np.nan])

## Dropping Values

In [59]:
s.dropna()

0    1.0
1    2.0
dtype: float64

## Filling nulls with a arbitrary values

In [60]:
s.fillna(0)

0    1.0
1    2.0
2    0.0
dtype: float64

## filling nulls with close values

In [61]:
# the method argument is used to fill null values with other values close to that null one
s.fillna(method = 'ffill')

/var/folders/zn/q9_l5xb11sd2s50rhjfnnmsm0000gn/T/ipykernel_29925/1151866447.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method = 'ffill')

0    1.0
1    2.0
2    2.0
dtype: float64

In [62]:
#now backwards fill
s.fillna(method = 'bfill')

/var/folders/zn/q9_l5xb11sd2s50rhjfnnmsm0000gn/T/ipykernel_29925/913945391.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method = 'bfill')

0    1.0
1    2.0
2    NaN
dtype: float64

## checking if there are NAs

In [63]:
#if there are missing values, s.dropna() will have less elements than s.
s.dropna().count()

np.int64(2)

In [64]:
players = pd.DataFrame({
    "name" : ['kobe bryant', 'lebron james', 'kobe bryant', 'carmelo anthony'],
    "position" : ['SG', 'SF', 'SG', 'SF']

})
players

              name position
0      kobe bryant       SG
1     lebron james       SF
2      kobe bryant       SG
3  carmelo anthony       SF

In [65]:
#the duplicated value returns true the second time the loop comes across it
players.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [66]:
# one can even be so accurate and use a subset
players.duplicated(subset = ["name"])

0    False
1    False
2     True
3    False
dtype: bool

## Text Handling

## lets explore most common invalid text cases

## Spliting columns

In [106]:
df = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})
df

              Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

#### You know that the single columns represent the values "year, Sex, Country and number of children", but it's all been grouped in the same column and separated by an underscore. Pandas has a convenient method named split that we can use in these situations:

In [92]:
df['Data'].str.split('_')

0       [1987, M, US , 1]
1       [1990?, M, UK, 1]
2        [1992, F, US, 2]
3    [1970?, M,    IT, 1]
4      [1985, F, I  T, 2]
Name: Data, dtype: object

In [93]:
df

              Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [97]:
# and if you want to create a dataframe out of your newly sorted dataframe
df['Data'].str.split('_',expand = True)

       0  1      2  3
0   1987  M    US   1
1  1990?  M     UK  1
2   1992  F     US  2
3  1970?  M     IT  1
4   1985  F   I  T  2

In [107]:
df = df['Data'].str.split('_', expand = True)

In [108]:
df.columns = ["Year", "Sex", "Country", "CH"]
df

    Year Sex Country CH
0   1987   M     US   1
1  1990?   M      UK  1
2   1992   F      US  2
3  1970?   M      IT  1
4   1985   F    I  T  2

In [110]:
# we see our year column contains row years that have '?' so we check it by using .contain()
df["Year"].str.contains('\?')

0    False
1     True
2    False
3     True
4    False
Name: Year, dtype: bool