In [1]:
# this is how to import pandas library
import pandas as pd

In [2]:
import numpy as np

## Pandas series

In [3]:
g7_pop = pd.Series([67.2, 65.3, 126.7, 60.7, 46.4, 64.6, 66.0])
g7_pop

0     67.2
1     65.3
2    126.7
3     60.7
4     46.4
5     64.6
6     66.0
dtype: float64

In [4]:
#series can also have a name which is useful for labeling data.
g7_pop.name = 'G7 Population in millions'
g7_pop

0     67.2
1     65.3
2    126.7
3     60.7
4     46.4
5     64.6
6     66.0
Name: G7 Population in millions, dtype: float64

In [5]:
g7_pop.dtype

dtype('float64')

In [6]:
#you can also check values of the series using the values attribute.
g7_pop.values

array([ 67.2,  65.3, 126.7,  60.7,  46.4,  64.6,  66. ])

In [7]:
g7_pop

0     67.2
1     65.3
2    126.7
3     60.7
4     46.4
5     64.6
6     66.0
Name: G7 Population in millions, dtype: float64

In [8]:
# you can also get elements of the series using the index attribute.
g7_pop[2]

np.float64(126.7)

In [9]:
g7_pop[0:4]

0     67.2
1     65.3
2    126.7
3     60.7
Name: G7 Population in millions, dtype: float64

In [10]:
# you can also set the index of the series using the index attribute.
g7_pop.index = [
    'canada',
    'france',
    'germany',
    'italy',
    'japan',
    'united kingdom',
    'united states'
]
g7_pop

canada             67.2
france             65.3
germany           126.7
italy              60.7
japan              46.4
united kingdom     64.6
united states      66.0
Name: G7 Population in millions, dtype: float64

In [11]:
# you can also bypass the creation of the series and create it directly with ordered dictionary.
g7_pop = pd.Series({
    'canada' : 67.2,
    'france' : 65.3,
    'germany' : 126.7,
    'italy' : 60.7,
    'japan' : 46.4,
    'united kingdom' : 64.6,
    'united states' : 66.0
}, name = 'G7 Population in millions')
g7_pop

canada             67.2
france             65.3
germany           126.7
italy              60.7
japan              46.4
united kingdom     64.6
united states      66.0
Name: G7 Population in millions, dtype: float64

## Indexing

In [12]:
# you can use the 'index' of the element you are looking for
g7_pop['germany']

np.float64(126.7)

In [13]:
g7_pop

canada             67.2
france             65.3
germany           126.7
italy              60.7
japan              46.4
united kingdom     64.6
united states      66.0
Name: G7 Population in millions, dtype: float64

In [14]:
# you can also get two elements of the series
g7_pop[['japan' , 'germany']]

japan       46.4
germany    126.7
Name: G7 Population in millions, dtype: float64

## Conditional Selection (boolean arrays)

In [15]:
g7_pop

canada             67.2
france             65.3
germany           126.7
italy              60.7
japan              46.4
united kingdom     64.6
united states      66.0
Name: G7 Population in millions, dtype: float64

In [16]:
g7_pop >= 73

canada            False
france            False
germany            True
italy             False
japan             False
united kingdom    False
united states     False
Name: G7 Population in millions, dtype: bool

## Operation and Methods

In [17]:
g7_pop

canada             67.2
france             65.3
germany           126.7
italy              60.7
japan              46.4
united kingdom     64.6
united states      66.0
Name: G7 Population in millions, dtype: float64

In [18]:
g7_pop = g7_pop * -1_000_000
g7_pop

canada            -67200000.0
france            -65300000.0
germany          -126700000.0
italy             -60700000.0
japan             -46400000.0
united kingdom    -64600000.0
united states     -66000000.0
Name: G7 Population in millions, dtype: float64

In [19]:
g7_pop.mean()

np.float64(-70985714.28571428)

In [20]:
g7_pop

canada            -67200000.0
france            -65300000.0
germany          -126700000.0
italy             -60700000.0
japan             -46400000.0
united kingdom    -64600000.0
united states     -66000000.0
Name: G7 Population in millions, dtype: float64

## Pandas DataFrame

In [21]:
# when creating a dataframe, you can pass a dictionary of series to the constructor. 
# The keys of the dictionary will be used as the column names 
# and the values will be used as the data for each column.
df = pd.DataFrame({
    'population': [67.2, 65.3, 126.7, 60.7, 46.4, 64.6, 66.0],
    'surface area': [9.985, 0.551, 0.357, 0.301, 0.378, 0.243, 9.834],
    'continent': [
        'South america', 
        'Asia',  
        'Europe', 
        'Europe',
        'Europe',
        'Europe',
        'North america'
    ]
})
df

   population  surface area      continent
0        67.2         9.985  South america
1        65.3         0.551           Asia
2       126.7         0.357         Europe
3        60.7         0.301         Europe
4        46.4         0.378         Europe
5        64.6         0.243         Europe
6        66.0         9.834  North america

In [22]:
#lets assign the index of the dataframe to be the country names.
df.index = [
    'canada',
    'france',
    'germany',
    'italy',
    'japan',
    'united kingdom',
    'united states'
] 
df

                population  surface area      continent
canada                67.2         9.985  South america
france                65.3         0.551           Asia
germany              126.7         0.357         Europe
italy                 60.7         0.301         Europe
japan                 46.4         0.378         Europe
united kingdom        64.6         0.243         Europe
united states         66.0         9.834  North america

In [23]:
## when getting the columns of a dataframe, 
# you can use the column name as an attribute of the dataframe.
df.columns

Index(['population', 'surface area', 'continent'], dtype='object')

In [24]:
# when getting the index of a dataframe, you can use the index attribute of the dataframe.
df.index

Index(['canada', 'france', 'germany', 'italy', 'japan', 'united kingdom',
       'united states'],
      dtype='object')

In [25]:
# when you want to get quick info about the dataframe, you can use the info() method of the dataframe.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, canada to united states
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   population    7 non-null      float64
 1   surface area  7 non-null      float64
 2   continent     7 non-null      object
dtypes: float64(2), object(1)
memory usage: 224.0+ bytes

In [26]:
# when getting size of the dataframe, you can use the shape attribute of the dataframe.
df.size

21

In [27]:
# when getting the shape of the dataframe, you can use the shape attribute of the dataframe.
df.shape

(7, 3)

In [28]:
# if you want to get the summary of the dataframe, you can use the describe() method of the dataframe.
df.describe()

       population  surface area
count    7.000000      7.000000
mean    70.985714      3.092714
std     25.581988      4.657918
min     46.400000      0.243000
25%     62.650000      0.329000
50%     65.300000      0.378000
75%     66.600000      5.192500
max    126.700000      9.985000

In [29]:
# when getting the types of the columns in the dataframe, you can use the dtypes attribute of the dataframe.
df.dtypes

population      float64
surface area    float64
continent        object
dtype: object

## Indexing, Selection and Slicing

In [30]:
df

                population  surface area      continent
canada                67.2         9.985  South america
france                65.3         0.551           Asia
germany              126.7         0.357         Europe
italy                 60.7         0.301         Europe
japan                 46.4         0.378         Europe
united kingdom        64.6         0.243         Europe
united states         66.0         9.834  North america

In [31]:
# when selecting individual rows of the dataframe, you can use the loc[] method of the dataframe.
df.loc['italy']

population        60.7
surface area     0.301
continent       Europe
Name: italy, dtype: object

In [32]:
# we use iloc[] method to select rows by their integer index.
df.iloc[-1]

population               66.0
surface area            9.834
continent       North america
Name: united states, dtype: object

In [33]:
df.iloc[3]

population        60.7
surface area     0.301
continent       Europe
Name: italy, dtype: object

In [34]:
df

                population  surface area      continent
canada                67.2         9.985  South america
france                65.3         0.551           Asia
germany              126.7         0.357         Europe
italy                 60.7         0.301         Europe
japan                 46.4         0.378         Europe
united kingdom        64.6         0.243         Europe
united states         66.0         9.834  North america

In [35]:
# when you want to select a column of the dataframe, you use the dataframe name 
# followed by the column name in square brackets.
df['continent']

canada            South america
france                     Asia
germany                  Europe
italy                    Europe
japan                    Europe
united kingdom           Europe
united states     North america
Name: continent, dtype: object

In [36]:
# you can also get a row (-up to) and a column by using the loc[] method of the dataframe.
df.loc['france' : 'united kingdom', 'population']

france             65.3
germany           126.7
italy              60.7
japan              46.4
united kingdom     64.6
Name: population, dtype: float64

In [40]:
#same using iloc[] method to get the same result as above.
df.iloc[1 : 5, 0]

france      65.3
germany    126.7
italy       60.7
japan       46.4
Name: population, dtype: float64

In [38]:
# the same as above but if you want to get two coloumns, you can pass a list of 
# column names to the loc[] method.
df.loc['france' : 'united kingdom', ['population', 'surface area']]

                population  surface area
france                65.3         0.551
germany              126.7         0.357
italy                 60.7         0.301
japan                 46.4         0.378
united kingdom        64.6         0.243

In [39]:
# this time using iloc[] method to get the same result as above.
df.iloc[1 : 5, [0, 1]]

         population  surface area
france         65.3         0.551
germany       126.7         0.357
italy          60.7         0.301
japan          46.4         0.378

In [42]:
countries = pd.dataframe({
    'china'
    'japan'
    'indonesia'
    'phillippines'
})
countries

AttributeError: module 'pandas' has no attribute 'dataframe'

## Conditional Selection

In [41]:
df

                population  surface area      continent
canada                67.2         9.985  South america
france                65.3         0.551           Asia
germany              126.7         0.357         Europe
italy                 60.7         0.301         Europe
japan                 46.4         0.378         Europe
united kingdom        64.6         0.243         Europe
united states         66.0         9.834  North america