## Reading External Data and Plotting

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# when you want read a csv file, we use the pd.read_csv() method
# for example, let's read the folder "data"
df = pd.read_csv('data/btc-market-price.csv')

In [6]:
# we use the .head() method to display the first  rows of the dataframe
df.head()

   2017-04-02 00:00:00  1099.169125
0  2017-04-03 00:00:00  1141.813000
1  2017-04-04 00:00:00  1141.600363
2  2017-04-05 00:00:00  1133.079314
3  2017-04-06 00:00:00  1196.307937
4  2017-04-07 00:00:00  1190.454250

In [7]:
# let's create new columns in the csv 'data' by using the .columns method
df.columns = ['Timestamp', 'Price']

In [8]:
df.head()

             Timestamp        Price
0  2017-04-03 00:00:00  1141.813000
1  2017-04-04 00:00:00  1141.600363
2  2017-04-05 00:00:00  1133.079314
3  2017-04-06 00:00:00  1196.307937
4  2017-04-07 00:00:00  1190.454250