## Reading External Data and Plotting

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# when you want read a csv file, we use the pd.read_csv() method
# for example, let's read the folder "data"
df = pd.read_csv('data/btc-market-price.csv')

In [4]:
# we use the .head() method to display the first  rows of the dataframe
df.head()

   2017-04-02 00:00:00  1099.169125
0  2017-04-03 00:00:00  1141.813000
1  2017-04-04 00:00:00  1141.600363
2  2017-04-05 00:00:00  1133.079314
3  2017-04-06 00:00:00  1196.307937
4  2017-04-07 00:00:00  1190.454250

In [5]:
# let's create new columns in the csv 'data' by using the .columns method
df.columns = ['Timestamp', 'Price']

In [10]:
# we use the .head() method to display the first  rows of the dataframe
# the first 5 rows of the dataframe
df.head()

             Timestamp        Price
0  2017-04-03 00:00:00  1141.813000
1  2017-04-04 00:00:00  1141.600363
2  2017-04-05 00:00:00  1133.079314
3  2017-04-06 00:00:00  1196.307937
4  2017-04-07 00:00:00  1190.454250

In [7]:
df.shape

(364, 2)

In [11]:
# we use the .tail() method to display the last  rows of the dataframe
# the last 5 rows of the dataframe
df.tail()

               Timestamp        Price
359  2018-03-28 00:00:00  7960.380000
360  2018-03-29 00:00:00  7172.280000
361  2018-03-30 00:00:00  6882.531667
362  2018-03-31 00:00:00  6935.480000
363  2018-04-01 00:00:00  6794.105000

In [12]:
df.dtypes

Timestamp     object
Price        float64
dtype: object

In [14]:
pd.to_datetime(df['Timestamp']).head()

0   2017-04-03
1   2017-04-04
2   2017-04-05
3   2017-04-06
4   2017-04-07
Name: Timestamp, dtype: datetime64[ns]

In [15]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [16]:
df.head()

   Timestamp        Price
0 2017-04-03  1141.813000
1 2017-04-04  1141.600363
2 2017-04-05  1133.079314
3 2017-04-06  1196.307937
4 2017-04-07  1190.454250

In [17]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

In [21]:
df.head()

                  Price
Timestamp
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937
2017-04-07  1190.454250

In [22]:
# let's check the price of bitcoin in 2017/09/29
df.loc['2017-09-29']

Price    4193.574667
Name: 2017-09-29 00:00:00, dtype: float64

## Summary Of What We Did So Far

In [23]:
df = pd.read_csv('data/btc-market-price.csv')
df.columns = ['Timestamp', 'Price'] 
pd.to_datetime(df['Timestamp']).head()
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

#### this should be much simpler and faster

In [24]:
pd.read_csv(
    'data/btc-market-price.csv',
    names=['Timestamp', 'Price'],
    header=0,
    index_col=0,
    parse_dates=True

)

                  Price
Timestamp
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937
2017-04-07  1190.454250
...                 ...
2018-03-28  7960.380000
2018-03-29  7172.280000
2018-03-30  6882.531667
2018-03-31  6935.480000
2018-04-01  6794.105000

[364 rows x 1 columns]